<?php
/**
 * KnowledgeBaseArticleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Service API
 *
 * ConnectWise Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Service;

/**
 * KnowledgeBaseArticleTest Class Doc Comment
 *
 * @category    Class */
// * @description KnowledgeBaseArticle
/**
 * @package     Spinen\ConnectWise\Clients\Service
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class KnowledgeBaseArticleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "KnowledgeBaseArticle"
     */
    public function testKnowledgeBaseArticle()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "issue"
     */
    public function testPropertyIssue()
    {

    }

    /**
     * Test attribute "resolution"
     */
    public function testPropertyResolution()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "business_unit_id"
     */
    public function testPropertyBusinessUnitId()
    {

    }

    /**
     * Test attribute "board_id"
     */
    public function testPropertyBoardId()
    {

    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {

    }

    /**
     * Test attribute "sub_category_id"
     */
    public function testPropertySubCategoryId()
    {

    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {

    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
