<?php
/**
 * ServiceNoteTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Service API
 *
 * ConnectWise Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Service;

/**
 * ServiceNoteTest Class Doc Comment
 *
 * @category    Class */
// * @description ServiceNote
/**
 * @package     Spinen\ConnectWise\Clients\Service
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServiceNoteTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ServiceNote"
     */
    public function testServiceNote()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "ticket_id"
     */
    public function testPropertyTicketId()
    {

    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {

    }

    /**
     * Test attribute "detail_description_flag"
     */
    public function testPropertyDetailDescriptionFlag()
    {

    }

    /**
     * Test attribute "internal_analysis_flag"
     */
    public function testPropertyInternalAnalysisFlag()
    {

    }

    /**
     * Test attribute "resolution_flag"
     */
    public function testPropertyResolutionFlag()
    {

    }

    /**
     * Test attribute "member"
     */
    public function testPropertyMember()
    {

    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {

    }

    /**
     * Test attribute "customer_updated_flag"
     */
    public function testPropertyCustomerUpdatedFlag()
    {

    }

    /**
     * Test attribute "process_notifications"
     */
    public function testPropertyProcessNotifications()
    {

    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {

    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {

    }

    /**
     * Test attribute "internal_flag"
     */
    public function testPropertyInternalFlag()
    {

    }

    /**
     * Test attribute "external_flag"
     */
    public function testPropertyExternalFlag()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
