<?php
/**
 * StatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Service API
 *
 * ConnectWise Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Service;

/**
 * StatusTest Class Doc Comment
 *
 * @category    Class */
// * @description Status
/**
 * @package     Spinen\ConnectWise\Clients\Service
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Status"
     */
    public function testStatus()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "board_id"
     */
    public function testPropertyBoardId()
    {

    }

    /**
     * Test attribute "sort_order"
     */
    public function testPropertySortOrder()
    {

    }

    /**
     * Test attribute "display_on_board"
     */
    public function testPropertyDisplayOnBoard()
    {

    }

    /**
     * Test attribute "inactive"
     */
    public function testPropertyInactive()
    {

    }

    /**
     * Test attribute "closed_status"
     */
    public function testPropertyClosedStatus()
    {

    }

    /**
     * Test attribute "time_entry_not_allowed"
     */
    public function testPropertyTimeEntryNotAllowed()
    {

    }

    /**
     * Test attribute "default_flag"
     */
    public function testPropertyDefaultFlag()
    {

    }

    /**
     * Test attribute "escalation_status"
     */
    public function testPropertyEscalationStatus()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
