<?php
/**
 * SurveyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Service API
 *
 * ConnectWise Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Service;

/**
 * SurveyTest Class Doc Comment
 *
 * @category    Class */
// * @description Survey
/**
 * @package     Spinen\ConnectWise\Clients\Service
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SurveyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Survey"
     */
    public function testSurvey()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "inactive_flag"
     */
    public function testPropertyInactiveFlag()
    {

    }

    /**
     * Test attribute "header_include_logo_flag"
     */
    public function testPropertyHeaderIncludeLogoFlag()
    {

    }

    /**
     * Test attribute "header_text"
     */
    public function testPropertyHeaderText()
    {

    }

    /**
     * Test attribute "header_text_visible_flag"
     */
    public function testPropertyHeaderTextVisibleFlag()
    {

    }

    /**
     * Test attribute "footer_text"
     */
    public function testPropertyFooterText()
    {

    }

    /**
     * Test attribute "footer_text_visible_flag"
     */
    public function testPropertyFooterTextVisibleFlag()
    {

    }

    /**
     * Test attribute "thank_you_text"
     */
    public function testPropertyThankYouText()
    {

    }

    /**
     * Test attribute "notify_who"
     */
    public function testPropertyNotifyWho()
    {

    }

    /**
     * Test attribute "notify_who_visible_flag"
     */
    public function testPropertyNotifyWhoVisibleFlag()
    {

    }

    /**
     * Test attribute "notify_member"
     */
    public function testPropertyNotifyMember()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
