<?php
/**
 * BoardStatusesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Service API
 *
 * ConnectWise Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Service;

use \Spinen\ConnectWise\Clients\Service\Configuration;
use \Spinen\ConnectWise\Clients\Service\ApiClient;
use \Spinen\ConnectWise\Clients\Service\ApiException;
use \Spinen\ConnectWise\Clients\Service\ObjectSerializer;

/**
 * BoardStatusesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BoardStatusesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for serviceBoardsIdStatusesCountGet
     *
     * .
     *
     */
    public function testServiceBoardsIdStatusesCountGet()
    {

    }

    /**
     * Test case for serviceBoardsIdStatusesGet
     *
     * .
     *
     */
    public function testServiceBoardsIdStatusesGet()
    {

    }

    /**
     * Test case for serviceBoardsIdStatusesPost
     *
     * .
     *
     */
    public function testServiceBoardsIdStatusesPost()
    {

    }

    /**
     * Test case for serviceBoardsIdStatusesStatusIdDelete
     *
     * .
     *
     */
    public function testServiceBoardsIdStatusesStatusIdDelete()
    {

    }

    /**
     * Test case for serviceBoardsIdStatusesStatusIdGet
     *
     * .
     *
     */
    public function testServiceBoardsIdStatusesStatusIdGet()
    {

    }

    /**
     * Test case for serviceBoardsIdStatusesStatusIdPatch
     *
     * .
     *
     */
    public function testServiceBoardsIdStatusesStatusIdPatch()
    {

    }

    /**
     * Test case for serviceBoardsIdStatusesStatusIdPut
     *
     * .
     *
     */
    public function testServiceBoardsIdStatusesStatusIdPut()
    {

    }

}
