<?php
/**
 * BoardTeamsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Service API
 *
 * ConnectWise Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Service;

use \Spinen\ConnectWise\Clients\Service\Configuration;
use \Spinen\ConnectWise\Clients\Service\ApiClient;
use \Spinen\ConnectWise\Clients\Service\ApiException;
use \Spinen\ConnectWise\Clients\Service\ObjectSerializer;

/**
 * BoardTeamsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BoardTeamsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for serviceBoardsIdTeamsCountGet
     *
     * .
     *
     */
    public function testServiceBoardsIdTeamsCountGet()
    {

    }

    /**
     * Test case for serviceBoardsIdTeamsGet
     *
     * .
     *
     */
    public function testServiceBoardsIdTeamsGet()
    {

    }

    /**
     * Test case for serviceBoardsIdTeamsPost
     *
     * .
     *
     */
    public function testServiceBoardsIdTeamsPost()
    {

    }

    /**
     * Test case for serviceBoardsIdTeamsTeamIdDelete
     *
     * .
     *
     */
    public function testServiceBoardsIdTeamsTeamIdDelete()
    {

    }

    /**
     * Test case for serviceBoardsIdTeamsTeamIdGet
     *
     * .
     *
     */
    public function testServiceBoardsIdTeamsTeamIdGet()
    {

    }

    /**
     * Test case for serviceBoardsIdTeamsTeamIdPatch
     *
     * .
     *
     */
    public function testServiceBoardsIdTeamsTeamIdPatch()
    {

    }

    /**
     * Test case for serviceBoardsIdTeamsTeamIdPut
     *
     * .
     *
     */
    public function testServiceBoardsIdTeamsTeamIdPut()
    {

    }

}
