<?php
/**
 * LocationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Service API
 *
 * ConnectWise Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Service;

use \Spinen\ConnectWise\Clients\Service\Configuration;
use \Spinen\ConnectWise\Clients\Service\ApiClient;
use \Spinen\ConnectWise\Clients\Service\ApiException;
use \Spinen\ConnectWise\Clients\Service\ObjectSerializer;

/**
 * LocationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LocationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for serviceLocationsCountGet
     *
     * .
     *
     */
    public function testServiceLocationsCountGet()
    {

    }

    /**
     * Test case for serviceLocationsGet
     *
     * .
     *
     */
    public function testServiceLocationsGet()
    {

    }

    /**
     * Test case for serviceLocationsIdDelete
     *
     * .
     *
     */
    public function testServiceLocationsIdDelete()
    {

    }

    /**
     * Test case for serviceLocationsIdGet
     *
     * .
     *
     */
    public function testServiceLocationsIdGet()
    {

    }

    /**
     * Test case for serviceLocationsIdPatch
     *
     * .
     *
     */
    public function testServiceLocationsIdPatch()
    {

    }

    /**
     * Test case for serviceLocationsIdPut
     *
     * .
     *
     */
    public function testServiceLocationsIdPut()
    {

    }

    /**
     * Test case for serviceLocationsPost
     *
     * .
     *
     */
    public function testServiceLocationsPost()
    {

    }

}
