<?php
/**
 * SurveysApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Service API
 *
 * ConnectWise Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Service;

use \Spinen\ConnectWise\Clients\Service\Configuration;
use \Spinen\ConnectWise\Clients\Service\ApiClient;
use \Spinen\ConnectWise\Clients\Service\ApiException;
use \Spinen\ConnectWise\Clients\Service\ObjectSerializer;

/**
 * SurveysApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Service
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SurveysApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for serviceSurveysCountGet
     *
     * .
     *
     */
    public function testServiceSurveysCountGet()
    {

    }

    /**
     * Test case for serviceSurveysGet
     *
     * .
     *
     */
    public function testServiceSurveysGet()
    {

    }

    /**
     * Test case for serviceSurveysIdDelete
     *
     * .
     *
     */
    public function testServiceSurveysIdDelete()
    {

    }

    /**
     * Test case for serviceSurveysIdGet
     *
     * .
     *
     */
    public function testServiceSurveysIdGet()
    {

    }

    /**
     * Test case for serviceSurveysIdPatch
     *
     * .
     *
     */
    public function testServiceSurveysIdPatch()
    {

    }

    /**
     * Test case for serviceSurveysIdPut
     *
     * .
     *
     */
    public function testServiceSurveysIdPut()
    {

    }

    /**
     * Test case for serviceSurveysPost
     *
     * .
     *
     */
    public function testServiceSurveysPost()
    {

    }

}
